### ISSUE TITLE
Working on Localhost / Browser?

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/PWA-burner-wallet#2]
Does it work for you guys on localhost?

I get this:

![image](https://github.com/BuidlGuidl/PWA-burner-wallet/assets/2486142/6e1cf408-ab76-40d8-8f50-1a4688343e8b)

----

But it works **on mobile** if I deploy it to Vercel (deploying a Sepolia contract). Should this work on the desktop browser or not?

**Comment by carletex** [comment]
cc @technophile-04 @Pabl0cks

**Comment by Pabl0cks** [comment]
This is working for me on desktop/localhost. I had problems the first time running it, trying on Chrome/Desktop, which was my first test.
After that first test, tried on Brave + Firefox and worked well, went back to Chrome and was also working. 

I've just tried on a fresh Firestore Database (was empty but never used), and worked on 3 navigators at the first try, will do more tests creating a new Firebase web app + new Firestore Database.

**Comment by technophile-04** [comment]
Yeah, Ideally it should work and works for me while testing on localhost on Chrome 

Carlos could you just try `Unregistring` the service worker from `Application` tab in the console and then refresh and try again? 


https://github.com/BuidlGuidl/PWA-burner-wallet/assets/80153681/67d3831c-4828-4b06-bdfc-e1a0abbfe507

Also another thing could you just try updating your VAPID's in `.env.local` by getting new ones by running `yarn web-push-generate` just looking at this [answer](https://stackoverflow.com/a/42385337/16480510).

I will try to reproduce this 🙌 by which will have clear rules, also will try to log helpfull logs while development so that its easy to debug 🙌

**Comment by Pabl0cks** [comment]
After the test of yesterday night that went OK, I ran more tests with these results:

**Fresh Firebase + Firestore**
- First execution in Chrome => **OK** (Allow notifs and Notif all, working as expected)
- Opened Firefox and Brave. Allow notif went OK, but when I *"Notify all"* I received no messages, and there were no errors.
- Switched back to Chrome, and it stopped working also (no error message, but I don't receive push notifs on screen)
- Stop the app in my bash console,  , `yarn start` again and now I received a `500 Internal Server Error` on the 3 browsers when trying to *"Notify all"*
- I killed my node processes, `yarn start` again and I received this error now when trying to *"Notify all"* => 
  ``` 
  body: 
  '{"code":401,"errno":109,"error":"Unauthorized","message":"Missing VAPID public key","more_info":"http://autopush.readthedocs.io/en/latest/http.html#error-codes"}',
    endpoint: 'https://updates.push.services.mozilla.com/wpush/v2/gAAAAABlHfAXBV1SeITRnUYYxJxruHn9SyQw7Sc2WJHKNhiKrZECa3v38IF83U5fUog1INftIh_JduN6jaf5n6MH3IyRGUT9Rgcv6h_HYpNiqxvU-adeKsnOsClaFO2Iaft66XHGcNxH4v0SeUKukWU9N1FIKe7PP3CATzFORNAPdM_ZyE7OwMw'
  }
  ```
- Generating new keys + updating `.env.local` + deleting old subscription pages in Firestore => It got fixed and couldn't get another error again. (**If you don't delete old Firestore subscriptions you get an error when *"Notify all"*, but you actually get the push notifications on the new devices**)

**New Fresh Firebase + Firestore environment**
- I can't make it stop working again with normal usage.
- **Special cases:**
  - When I reset notification permissions on Chrome for localhost, when I hit *"Allow notifs"* I get a `Service Worker not registered` error, but refreshing the page and clicking the button again, now it works. (Could not manage to reproduce that either on following tries of deleting notification permissions)
  - When you delete notification permissions, it does not actually remove the subscription page on Firestore until you hit the *"Notify all"* button to send a new notification. By doing that, the log shows `4 messages sent`, but then removes the old one, and you don't get an error on that one, so I guess is before actually pushing the notification.
  - When I stop the app in my bash console,  , and `yarn start` again, somtimes I get the I receive `500 Internal Server Error` and sometimes I get directly the `{"code":401,"errno":109,"error":"Unauthorized","message":"Missing VAPID public key"`.   
  **I need to recreate keys, update them and delete old subscriptions.**

Overall errors seem a bit random, but for the final user when this happends it will ruin their notifications.  
Even if we refresh VAPID keys and delete old subscriptions, users will not delete permissions and allow them again, so they won't receive anything (althought the app seems subscribed in the front-end for them)

**Comment by carletex** [comment]
Thank you both for the tests & research!

> Carlos could you just try Unregistring the service worker from Application tab in the console and then refresh and try again?

Keeps failing on Brave :(

Tried to regenerate VAPID, change env vars, clear firestore data, reset yarn start.... and still failing :/

Tried on firefox... and it works :unamused: 

Getting this error tho (but I get the notification on firefox... I guess it's failing to send it to other devices.)
![image](https://github.com/BuidlGuidl/PWA-burner-wallet/assets/2486142/f16b367a-2a30-42ec-9e03-4eea3a52c8e2)


But the Vercel deployment works for me again (maybe because cleaning the subscription data on firestore?) I'm using the same firestore in localhost & Vercel

**Comment by technophile-04** [comment]
@carletex  from this https://github.com/BuidlGuidl/PWA-burner-wallet/issues/2#issue-1926639827 image, when I initially installed brave and tried Subscribing on localhost:3000 I was also getting the same error but when I turned on “Use Google services for push messaging” it worked and didn't fail after that localhost : 

![Screenshot 2023-10-06 at 11 31 10 AM](https://github.com/BuidlGuidl/PWA-burner-wallet/assets/80153681/4c8b47da-5d76-4903-9793-ed594943a5db)

Was mentioned here => https://community.brave.com/t/push-notifications-not-working-registration-failed-push-service-error/314471

Also could please try testing this in new PR branch => https://github.com/BuidlGuidl/PWA-burner-wallet/pull/4

**Comment by carletex** [comment]
> @carletex from this https://github.com/BuidlGuidl/PWA-burner-wallet/issues/2#issue-1926639827 image, when I initially installed brave and tried Subscribing on localhost:3000 I was also getting the same error but when I turned on “Use Google services for push messaging” it worked and didn't fail after that localhost :

That was it! Thanks Shiv :)

**Comment by carletex** [comment]
Closing this one
