### ISSUE TITLE
Built with SE-2 thumbnail

### ISSUE THREAD

**Issue by andrealbiac** [BuidlGuidl/PWA-burner-wallet#6]
Hey! Dropping here two versions of the PWA thumbnail, 

Which one do you guys prefer? C:

![social card-1](https://github.com/BuidlGuidl/PWA-burner-wallet/assets/137904915/e260c62d-9de7-43f8-b8f7-c22f05e78bbc)
![social card](https://github.com/BuidlGuidl/PWA-burner-wallet/assets/137904915/31fee06b-5656-4615-8299-49ef661d1323)

**Comment by technophile-04** [comment]
I like the first one, kind of gives the "Burner" wallet feel with that orange tint but the seconds one looks nice too !!

**Comment by carletex** [comment]
Also like the first one!
